import { Platform, StatusBar, StyleSheet } from 'react-native';
import colors from '../../../theme/colors';

export const styles = StyleSheet.create({
  centerElement: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  keyBoardView: {
    flex: 1,
    marginTop: Platform.OS === 'ios' ? 40 : StatusBar.currentHeight,
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#eaeef1',
  },
  header: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    marginBottom: 10,
  },
  backButton: {
    width: 50,
    height: 50,
  },
  headerTitle: {
    height: 50,
  },
  headerTitleText: {
    fontSize: 18,
    color: '#000',
  },
  progressBar: {
    alignItems: 'center',
    elevation: 10,
    borderBottomWidth: 1,
    borderColor: '#ddd',
  },
  progressBarInner: {
    width: 280,
    height: 70,
  },
  progressLine: {
    height: 2,
    backgroundColor: colors.primary,
    width: 180,
    position: 'absolute',
    top: 13,
    zIndex: 10,
  },
  stepContainer: {
    flexDirection: 'row',
    width: '100%',
    position: 'absolute',
    zIndex: 20,
  },
  stepItem: {
    alignItems: 'center',
    width: 70,
  },
  stepCircle: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    backgroundColor: '#eaeef1',
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 15,
    marginBottom: 10,
  },
  stepText: {
    fontSize: 12,
    color: '#6689ff',
  },
  inputContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    backgroundColor: '#26d06e',
    borderWidth: 2,
    borderColor: '#26d06e',
    borderRadius: 15,
    marginBottom: 10,
  },
  inputLabel: {
    marginBottom: 5,
    fontSize: 12,
    position: 'absolute',
    left: 15,
    top: -9,
    paddingHorizontal: 6,
    backgroundColor: '#fff',
    zIndex: 10,
    color: '#6689ff',
  },
  input: {
    width: '100%',
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#6689ff',
  },
  paymentMethodContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  paymentMethodImage: {
    width: 70,
    height: 60,
    marginLeft: 5,
    resizeMode: 'contain',
  },
  button: {
    marginVertical: 10,
    width: 80,
    height: 35,
    elevation: 5,
    borderRadius: 20,
  },
  buttonText: {
    color: '#fff',
  },
  nextButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 80,
    height: 35,
    backgroundColor: colors.primary,
    elevation: 5,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  prevButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    width: 80,
    height: 35,
    backgroundColor: colors.secondary,
    elevation: 5,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selected: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 15,
    marginBottom: 10,
  },
  map: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    marginBottom: 2,
    height: 70,
    paddingHorizontal: 20,
  },
  mapInner: {
    flexDirection: 'row',
    flexGrow: 1,
    flexShrink: 1,
    alignSelf: 'center',
  },
  productImage: {
    height: 60,
    width: 60,
    backgroundColor: '#eeeeee',
  },
  productName: {
    flexGrow: 1,
    flexShrink: 1,
    alignSelf: 'center',
  },
  subTotalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  productInfo: {
    flexDirection: 'row',
    paddingTop: 15,
    justifyContent: 'space-between',
  },
  navigationButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'relative',
    height: 60,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
});
